project:
  type: book
  output-dir: docs
book:
  title: "Kioloa PopGen"
  author: "Bernd Gruber, Arthur Georges, Carlo Pacioni, Luis Mijangos"
  date: "02/28/2024"
  chapters:
    - index.qmd
    - schedule.qmd
    - install.qmd
    - session01.qmd
    - session02.qmd
    - session10.qmd
    - references.qmd
    - break.qmd
    - tutorials.qmd

bibliography: references.bib
highlight-style: pygments

format:

  html:
    theme: cosmo
    css: "css.css"
    number-sections: false

editor: visual
