---
format: html
editor: visual
---

# Program {.unnumbered}

*for a more detailed program see the* [More Info](useful.qmd) *section*

| \#  | Day |     Time     |                         **Topic**                          |                                 Presenters                                 |
|:-------------:|---------------|:-------------:|:-------------:|:-------------:|
|  1  | Mon | 2 pm - 4 pm  |         [**Welcome, Intro dartR**](session01.qmd)          | Oliver Berry, Andrzej Killian, Arthur Georges, Bernd Gruber, Renee Catullo |
|  2  |     | 5 pm – 7 pm  | [**Pop Gen In Conservation & Restoration**](session02.qmd) |                 Bill Sherwin, Carlo Pacioni, Renee Catullo                 |
|  3  | Tue | 9 am – 11 am |                [**Sequencing Technologies**](session03.qmd)                 |               Jason Carling, Andrew Kowalczyk, Renee Catullo               |
|  4  |     | 12 pm – 2 pm |      [**Data Management, Reproducibility & Integrity**](session04.qmd)      |                                 Jiajia Li                                  |
|  5  |     | 3 pm – 5 pm  |       [**Effective Population Size**](session05.qmd)       |                 Bernd Gruber, Carlo Pacioni, Bill Sherwin                  |
|  6  | Wed | 9 am – 11 am |    [**Management Of Small Populations**](session06.qmd)    |                    Catherine Grueber, Kate Farquharson                     |
|  7  |     | 12 pm – 2 pm |                   [**Natural Selection**](session07.qmd)                    |            Luciano Beheregaray, Chris Brauer, Jonathan Sandoval            |
|  8  |     | 3 pm – 5 pm  |          [**Landscape Genetics**](session08.qmd)           |                          Bernd Gruber, Robyn Shaw                          |
|  9  | Thu | 9 am – 11 am |                   [**Lineage Divergence**](session09.qmd)                   |                 Arthur Georges, Sally Potter, Craig Moritz                 |
| 10  |     | 12 pm – 2 pm |          [**Sex Linked Markers**](session10.qmd)           |                    Diana Robledo, Floriaan Devloo-Delva                    |
| 11  |     | 7 pm – 9 pm  |  [**From Genes to Kin: Dissecting Relatedness & Kinship**](session11.qmd)   |                Jinliang Wang, Luis Mijangos, Natasha Marosi                |
| 12  | Fri | 9 am – 11 am |                   [**Genetic Structure**](session12.qmd)                    |                 Arthur Georges, Bernd Gruber, Bill Sherwin                 |
| 13  |     | 12 pm – 2 pm |              [**Combining Genomic Resources**](session13.qmd)               |                        Luis Mijangos, Sally Potter                         |

: {tbl-colwidths="\[5,5,20, 30, 40\]" .striped .bordered}
